app/routes/create_item.py
from flask import (
    Blueprint, 
    render_template, 
    request, 
    flash, 
    url_for, 
    redirect
    )

from ..models.inventory_model import InventoryModel

from ..extensions import db

from ..extensions import login_required

create_bp = Blueprint('create_item', __name__)

@create_bp.route('/create')
@login_required
def create():
    return render_template('create_item.html')

@create_bp.route('/create_item', methods=['POST', 'GET'])
@login_required
def create_item():

    if request.method == 'POST':

        error = None

        name = request.form['name']
        description = request.form['description']
        price = float(request.form['price'])
        quantity = int(request.form['quantity'])

        if not name:
            error = 'Name cannot be empty'
        elif not description:
            error = 'Description cannot be empty'
        elif not price:
            error = 'Price cannot be empty'
        elif not quantity:
            error = 'Quantity cannot be empty'

        if error is None:
            _columns = InventoryModel(
                        name=name,
                        description=description,
                        price=price,
                        quantity=quantity
                        )
            db.session.add(_columns)
            db.session.commit()

            return redirect(url_for('index.index'))

        flash(error)

    return render_template('create_item.html')

app/routes/delete_item.py
from flask import (
    Blueprint, 
    render_template, 
    request, 
    jsonify, 
    url_for,
    redirect
    )

from ..models.inventory_model import InventoryModel

from ..extensions import db

delete_bp = Blueprint('delete_item', __name__)

@delete_bp.route('/delete_item/<int:id>/')
def delete_item(id):
    _item_ = InventoryModel.query.filter_by(id=id).one()

    db.session.delete(_item_)
    db.session.commit()
    return redirect(url_for('index.index'))

    # Get form data
    # item_id = int(request.form['id'])
    # Delete from database
    # conn = sqlite3.connect('inventory.db')
    # c = conn.cursor()
    # c.execute("DELETE FROM items WHERE id=?", (item_id,))
    # conn.commit()
    # conn.close()

    # return jsonify({'success': True})

app/routes/login.py
from flask import (
    Blueprint, 
    render_template, 
    request,
    flash,
    url_for, 
    redirect
    )

from ..extensions import db

from ..models.user_management import User

from werkzeug.security import check_password_hash

from ..extensions import login_required, login_user


login_bp = Blueprint('login', __name__)

@login_bp.route('/login')
def login():
    return render_template('auth/login.html')


@login_bp.route('/login/user', methods=['POST', 'GET'])
def login_existing_user():

    if request.method == 'POST':
        error = None
        email = request.form['email']
        password = request.form['password']

        user_ = User.query.filter_by(email=email).first()

        if user_ is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user_.password, password):
            error = 'Incorrect password.'
        

        if error is None:
            login_user(user_)
            return redirect(url_for('index.index'))
    
        flash(error)
    
    return render_template('auth/login.html')

app/routes/logout.py
from flask import (
    Blueprint,
    request,
    url_for, 
    redirect
    )

from ..extensions import login_required, logout_user

logout_bp = Blueprint('logout', __name__)

@logout_bp.route('/logout', methods=['POST', 'GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('login.login'))

app/routes/register.py
from flask import (
    Blueprint, 
    render_template, 
    request,
    url_for, 
    redirect,
    flash
    )
from ..extensions import db

from ..models.user_management import User

from werkzeug.security import generate_password_hash

register_bp = Blueprint('register', __name__)

@register_bp.route('/register')
def register():
    return render_template('auth/register.html')

@register_bp.route('/register/new_user', methods=['POST', 'GET'])
def register_new_user():

    if request.method == 'POST':

        error = None

        first_name = request.form['first_name']
        last_name = request.form['last_name']
        username = request.form['username']
        email = request.form['email']
        password = generate_password_hash(request.form['password'])

        user_ = User.query.filter_by(username=username).first()

        if not first_name:
            error = 'First Name cannot be empty'
        elif not last_name:
            error = 'Last Name cannot be empty'
        elif not username:
            error = 'Username cannot be empty'
        elif not email:
            error = 'Email cannot be empty'
        elif user_ is not None:
            error = f'Username {user_.username} is already registered. Create a new one.'
        
        if error is None:
            user = User(
                first_name=first_name,
                last_name=last_name,
                username=username,
                email=email,
                password=password
                )
            db.session.add(user)
            db.session.commit()

            return redirect(url_for('login.login'))

        flash(error)

    return render_template('auth/register.html')

app/routes/update_item.py
from flask import (
    Blueprint, 
    render_template, 
    request, 
    jsonify, 
    url_for, 
    redirect
    )

from ..models.inventory_model import InventoryModel

from ..extensions import db

update_item_bp = Blueprint('update_item', __name__)

@update_item_bp.route('/update/<int:id>/')
def update(id):

    product = InventoryModel.query.filter_by(id=id).one()

    return render_template('update_item.html', product=product)

@update_item_bp.route('/update_item/<int:id>/', methods=['POST', 'GET'])
def update_item(id):
    # Get data

    product = InventoryModel.query.filter_by(id=id).one()

    if request.method == 'POST':

        error = None

        name = request.form['name']
        description = request.form['description']
        price = float(request.form['price'])
        quantity = int(request.form['quantity'])

        column_of_data = [name, description, price, quantity]

        for element in column_of_data:
            if element is None:
                error = 'Input cannot be empty'
                if error is not None:
                    flash(error)
            else:
                product.name = name
                product.description = description
                product.price = price
                product.quantity = quantity

                db.session.commit()

                return redirect(url_for('index.index'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Inventory System{% endblock %}</title>
    <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='/css/styles.css') }}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('index.index') }}">Inventory System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('index.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('create_item.create') }}">Add Item</a>
                </li>
                {% if current_user.is_authenticated %}
                  <li class="nav-item nav-link">Hi {{ current_user.first_name }}</li>
                  <li class="nav-item"><a href="{{ url_for('logout.logout') }}" class="nav-link">Log Out</a></li>
                {% else %}
                <li class="nav-item"><a href="{{ url_for('login.login') }}" class="nav-link">Log In</a></li>
                <li class="nav-item"><span class="nav-link">|</span></li>
                <li class="nav-item"><a href="{{ url_for('register.register')}}" class="nav-link">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mt-5 c-data">
        {% block content %}{% endblock %}
    </div>

<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- Bootstrap JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/create_item.html
{% extends 'base.html' %}

{% block content %}
<h2 class="mb-3 sm-mb-3">Add Item</h2>
  {% for messages in get_flashed_messages() %}
    <div class="alert alert-danger mb-3 sm-mb-3">{{ message }}</div>
  {% endfor %}
<form method="POST" action="{{ url_for('create_item.create_item') }}">
    <div class="form-group">
        <label>Name</label>
        <input type="text" class="form-control" name="name" required>
    </div>
    <div class="form-group">
        <label>Description</label>
        <textarea class="form-control" name="description" rows="3"></textarea>
    </div>
    <div class="form-group">
        <label>Price</label>
        <input type="number" class="form-control" name="price" required>
    </div>
    <div class="form-group">
        <label for="quantity">Quantity</label>
        <input type="number" class="form-control" id="quantity" name="quantity" required>
    </div>
    <button type="submit" class="btn btn-primary">Add Item</button>
</form>
{% endblock %}

app/templates/delete_item.html
{% extends 'base.html' %}

{% block content %}
<h2>Delete Item</h2>
<p>Are you sure you want to delete {{ item_.name }}?</p>
<form method="POST" action="{{ url_for('delete_item.delete_item', id=item_.id) }}">
    <button type="submit" class="btn btn-danger">Delete Item</button>
</form>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Items</h2>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <!-- <th>Product_ID</th> -->
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>DateTime</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for column in columns %}
        <tr>
            <td>{{ column.id }}</td>
            <!-- <td>{{ column.product_id }}</td>s -->
            <td>{{ column.name }}</td>
            <td>{{ column.description }}</td>
            <td>{{ column.price }}</td>
            <td>{{ column.quantity }}</td>
            <td>{{ column.date }}</td>
            <td>
                <a href="{{ url_for('update_item.update', id=column.id) }}"><i class="fas fa-edit"></i></a>
                <a href="{{ url_for('delete_item.delete_item', id=column.id) }}" onclick="return confirm('Are you sure you want to delete this item?')"><i class="fas fa-trash-alt"></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/update_item.html
{% extends 'base.html' %}

{% block content %}
    <h2>Add Item</h2>
    {% if product %}
    <form method="POST" action="{{ url_for('update_item.update_item', id=product.id) }}">
        <div class="form-group">
            <label>Name</label>
            <input type="text" class="form-control" name="name" value="{{ product.name or request.form['name'] }}" required>
        </div>
        <div class="form-group">
            <label>Description</label>
            <textarea class="form-control" name="description" rows="3">{{ product.description or request.form['description'] }}</textarea>
        </div>
        <div class="form-group">
            <label>Price</label>
            <input type="number" class="form-control" name="price" value="{{ product.price or float(request.form['price']) }}" required>
        </div>
        <div class="form-group">
            <label for="quantity">Quantity</label>
            <input type="number" class="form-control" id="quantity" value="{{ product.quantity or int(request.form['quantity']) }}" name="quantity" required>
        </div>
        <button type="submit" class="btn btn-primary">Add Item</button>
    </form>
    {% endif %}
{% endblock %}